### ISSUE TITLE
Update to new version of fge/json-schema-validator

### ISSUE THREAD

**Issue by PascalBru** [sabina-jung/JSON-Schema-Validation-Eclipse#3]
Use the newest version (2.0.1) of json-schema-validator from fge/json-schema-validator

**Comment by PascalBru** [comment]
update pom.xml and make changes in the denpending files

also add a property page in the project for easier access

**Comment by paulvi** [comment]
@PascalBru are you interested in newer version?

**Comment by PascalBru** [comment]
Yes do you have one?

**Comment by paulvi** [comment]
@jcompagner has fork at https://github.com/Servoy/JSON-Schema-Validation-Eclipse, see #8
I guess we should treat some repository as main as close issues here, as author is not responding anyways.

There is also newer effort, that is related at https://github.com/angelozerr/eclipse-wtp-json
